"""add phone and password to users

Revision ID: 80545f948807
Revises: df1b19823280
Create Date: 2026-05-14 14:30:32.665669

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '80545f948807'
down_revision: Union[str, None] = 'df1b19823280'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'users', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'password')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###